spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://journey.cgwc3atjaolu.eu-north-1.rds.amazonaws.com:3306/journey
    username: admin
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

api:
  ai:
    getAccessToken:
      url: https://aip.baidubce.com/oauth/2.0/token
      grantType: client_credentials
      clientId: x5ElkR5OBBSRZbyDMm0dIYvL
      clientSecret: F2aAk53KPLTWQjY7T2G3C2HEnKb05Yuq
    answer:
      url: https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/eb-instant
  weather:
    url: https://weatherapi-com.p.rapidapi.com/current.json
    key: ff4f5cd3a6mshaae92fcc4c9b174p165136jsn644f4d752007
    host: weatherapi-com.p.rapidapi.com
  airbnb:
    url: https://airbnb13.p.rapidapi.com/search-location
    key: ff4f5cd3a6mshaae92fcc4c9b174p165136jsn644f4d752007
    host: airbnb13.p.rapidapi.com
